import { ELSClient, type ELSConfig, type ErrorEntry } from "@inso_web/els-client";

/**
 * ELS (Event Logging Service) wiring.
 *
 * The ingest endpoint is a fixed public URL (hard-coded). Only the API key is
 * a secret: it is injected at build time (vite `define`, see vite.config.ts)
 * from a CI secret variable — never committed to the repo. When the key is
 * missing (local/dev/contributor builds), ELS is disabled and every helper
 * here is a silent no-op, so the extension works without it.
 *
 * We send via `sendError` (not the Pino-style logger methods) because those
 * hard-code `source:"server"`; sendError lets us set `source:"client"` and
 * attach diagnostics. What we send: explicit product events (mirrored from
 * analytics) and errors/stacktraces, plus non-sensitive client diagnostics
 * (userAgent, language, screen/viewport size, sessionId). We never include OPFS
 * file names/paths/contents, typed text, the inspected page URL/origin, or PII.
 */

const ENDPOINT = __ELS_ENDPOINT__ || "https://api.insoweb.ru/els";
const API_KEY = __ELS_API_KEY__;

// Session id — generated by the extension (the SDK does not create one), so all
// events/errors from one running surface can be correlated server-side.
function makeSessionId(): string {
  try {
    if (typeof crypto !== "undefined" && crypto.randomUUID) {
      return crypto.randomUUID();
    }
  } catch {
    /* ignore */
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
const SESSION_ID = makeSessionId();

export const elsConfig: ELSConfig | null = API_KEY
  ? {
      endpoint: ENDPOINT,
      apiKey: API_KEY,
      appSlug: "opfs-studio",
      serviceName: "opfs-studio-extension",
      deploymentEnv: __ELS_ENV__,
      appVersion: __APP_VERSION__,
    }
  : null;

export const elsClient: ELSClient | null = (() => {
  if (!elsConfig) return null;
  try {
    return new ELSClient(elsConfig);
  } catch {
    return null;
  }
})();

/** Non-sensitive client diagnostics attached to every entry. */
function baseEntry(): Partial<ErrorEntry> {
  const b: Partial<ErrorEntry> = {
    source: "client",
    sessionId: SESSION_ID,
    url: "chrome-extension://opfs-studio",
  };
  try {
    if (typeof location !== "undefined" && location.href) b.url = location.href;
  } catch {
    /* ignore */
  }
  try {
    if (typeof navigator !== "undefined") {
      b.userAgent = navigator.userAgent;
      b.language = navigator.language;
    }
  } catch {
    /* ignore */
  }
  try {
    if (typeof screen !== "undefined") {
      b.screenSize = `${screen.width}x${screen.height}`;
    }
  } catch {
    /* ignore */
  }
  try {
    if (typeof window !== "undefined") {
      b.viewportSize = `${window.innerWidth}x${window.innerHeight}`;
    }
  } catch {
    /* ignore */
  }
  try {
    if (typeof document !== "undefined" && document.referrer) {
      b.referrer = document.referrer;
    }
  } catch {
    /* ignore */
  }
  return b;
}

/** Log a product event. No-op when ELS is disabled. */
export function elsEvent(name: string, params?: Record<string, string>): void {
  if (!elsClient) return;
  try {
    void elsClient.sendError({
      ...baseEntry(),
      message: name,
      level: "info",
      errorCategory: "event",
      // whitelisted params (theme/lang/ext/kind/count) ride along as custom fields
      ...(params ?? {}),
    } as ErrorEntry);
  } catch {
    // fire-and-forget
  }
}

/** Report an error / stacktrace. No-op when ELS is disabled. */
export function elsError(
  err: unknown,
  context?: string,
  componentStack?: string
): void {
  if (!elsClient) return;
  try {
    const isErr = err instanceof Error;
    void elsClient.sendError({
      ...baseEntry(),
      message: isErr ? err.message : String(err),
      stack: isErr ? err.stack : undefined,
      componentStack,
      level: "error",
      errorCategory: context,
    } as ErrorEntry);
  } catch {
    // fire-and-forget
  }
}
